name: 'CI'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - { target: x86_64-unknown-linux-musl, amd64-linux, os: ubuntu-latest }
          - { target: wasm32-wasi, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-2019 }
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.job.target }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --locked --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.job.target }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

      - name: Check format
        run: cargo fmt -- --check
